dayoff/urls.py
from django.urls import path

from dayoff import views

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.my_login, name='login'),
    path('create/', views.create, name='create-dayoff'),
]

polls/urls.py
from django.urls import path

from polls import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.my_login, name="login"),
    path("logout", views.my_logout, name="logout"),
    path("change_password", views.change_password, name="change_password"),
    path("register", views.register, name="register"),
    path("detail/<int:poll_id>/", views.detail, name="poll_detail"),
    path("detail/<int:poll_id>/create-comment", views.create_comment, name="create_comment"),
    path('detail/<int:question_id>/choice/', views.edit_choice, name='update_choice'),
    path('detail/<int:question_id>/choice/api/', views.edit_choice_api, name='update_choice_api'),
    path("create/", views.create, name='create_poll'),
    path("update/<int:poll_id>/", views.update, name='update_poll'),
    path("delete/<int:question_id>/", views.delete_question, name='delete_question'),
]

webpro2018django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('dayoff/', include('dayoff.urls')),
]

dayoff/models.py
from django.contrib.auth.models import User
from django.db import models


class Dayoff(models.Model):
    create_by = models.ForeignKey(User, db_column='create_by', on_delete=models.CASCADE, verbose_name='ขอลาโดย')
    reason = models.TextField(blank=False, null=True, verbose_name='เนื่องจาก')

    type_choice = (
        (0, 'ลากิจ'),
        (1, 'ลาป่วย'),
    )

    type = models.SmallIntegerField(choices=type_choice, default=0, verbose_name='ประเภท')

    date_start = models.DateField(blank=False, null=True, verbose_name='ตั้งแต่วันที่')
    date_end = models.DateField(blank=False, null=True, verbose_name='ถึงวันที่')

    approve_status_choice = (
        (0, 'อนุมัติ'),
        (1, 'ไม่อนุมัติ'),
        (2, 'รอการอนุมัติ'),
    )
    approve_status = models.SmallIntegerField(choices=approve_status_choice, default=2, verbose_name='อนุมัติ')

    class Meta:
        db_table = 'dayoff'

dayoff/forms.py
from django import forms
from django.core.exceptions import ValidationError

from dayoff.models import Dayoff

import datetime


class DayOffForm(forms.ModelForm):
    class Meta:
        model = Dayoff
        exclude = ['approve_status', 'create_by']
        widgets = {
            'reason': forms.Textarea(attrs={'class': 'form-control'}),
            'type': forms.Select(attrs={'class': 'form-control'}),
            'date_start': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'date_end': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
        }

    def clean(self):
        data = super().clean()

        start = data.get('date_start')
        end = data.get('date_end')


        if start > end:
            raise ValidationError('End date cannot come before start date')
        elif start < datetime.datetime.now().date():
            raise ValidationError('Please do not fill date in past')

dayoff/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.shortcuts import render, redirect

from dayoff.models import Dayoff
from dayoff.forms import DayOffForm


def index(request):
    context = {}

    try:
        context['dayoff_list'] = Dayoff.objects.all().filter(
            create_by=User.objects.get(username=request.user.username)
        )
    except User.DoesNotExist:
        context['dayoff_list'] = None

    return render(request, template_name='dayoff/index.html', context=context)


def create(request):
    context = {}

    if request.method == 'POST':
        form = DayOffForm(request.POST)
        if form.is_valid():
            Dayoff.objects.create(
                reason=form.cleaned_data.get('reason'),
                type=form.cleaned_data.get('type'),
                date_start=form.cleaned_data.get('date_start'),
                date_end=form.cleaned_data.get('date_end'),
                create_by=User.objects.get(username=request.user.username)
            )
            return redirect('index')

    else:
        form = DayOffForm()

    context['form'] = form

    return render(request, template_name='dayoff/create.html', context=context)


def my_login(request):
    context = {}

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        # Login success null if failed
        if user:
            login(request, user)

            next_url = request.POST.get('next_url')

            if next_url:
                return redirect(next_url)

            if user.groups.filter(name='Manager').exists():
                return redirect('/admin')
            return redirect('index')

        else:
            context['username'] = username
            context['error'] = 'Wrong username or password'

    next_url = request.GET.get('next')
    if next_url:
        context['next_url'] = next_url

    return render(request, 'dayoff/login.html', context=context)

dayoff/templates/dayoff/create.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta http-equiv="X-UA-Compatible" content="ie=edge"/>
    <title>Day Off Request</title>
    <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
            integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
            crossorigin="anonymous"
    />
    <link href="{% static 'css/main.css' %}" rel="stylesheet" type="text/css"/>
</head>
<body>
<div>
    <h1 class="text-center mt-4">สร้างใบลา</h1>
    {% if form.non_field_errors %}
        <div class="container">
            <div class="row">
                <div class="col">
                    <div class="alert alert-danger" role="alert">
                        {% for error in form.non_field_errors %}
                            {{ error }} <br/>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    {% endif %}


    <form
            class="container"
            method="POST"
            action="{% url 'create-dayoff' %}"
    >
        {% csrf_token %}

        <div class="form-group">
            {{ form.reason.label }}
            {{ form.reason }}
        </div>
        <div class="form-group">
            {{ form.type.label }}
            {{ form.type }}
        </div>
        <div class="form-group">
            {{ form.date_start.label }}
            {{ form.date_start }}
        </div>
        <div class="form-group">
            {{ form.date_end.label }}
            {{ form.date_end }}
        </div>

        <div class="center group">
            <input class="btn btn-success" type="submit" value="Submit"/>
            <a href="{% url 'index' %}">
                <input class="btn btn-danger" type="button" value="Back"/>
            </a>
        </div>
    </form>
</div>
</body>
</html>

dayoff/templates/dayoff/index.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta http-equiv="X-UA-Compatible" content="ie=edge"/>
    <title>Day Off</title>
    <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
            integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
            crossorigin="anonymous"
    />
    <link href="{% static 'css/main.css' %}" rel="stylesheet" type="text/css"/>
</head>
<body>
<div>
    <div class="text-center mt-4">
        <h1>ระบบลา</h1>
        <h2>รายการ</h2>
    </div>


    {% if user.is_authenticated %}
        <div class="container poll-list">
            {% if success %}
                <div class="alert alert-success text-center container">
                    {{ success }}
                </div>
            {% endif %}
            <table class="table">
                <tr>
                    <th>ประเภท</th>
                    <th>เหตุผล</th>
                    <th>จากวันที่</th>
                    <th>ถึงวันที่</th>
                    <th>สถาณะ</th>
                </tr>
                {% for dayoff in dayoff_list %}
                    <tr>
                        <td>
                            {{ dayoff.get_type_display }}
                        </td>
                        <td>
                            {{ dayoff.reason }}
                        </td>
                        <td>
                            {{ dayoff.date_start }}
                        </td>
                        <td>
                            {{ dayoff.date_end }}
                        </td>
                        <td>
                            {{ dayoff.get_approve_status_display }}
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    {% else %}
        <div class="alert alert-warning center container narrow">
            เข้าสู่ระบบก่อนสิ! จะลายังขี้เกียจอีก
        </div>
    {% endif %}

    <div class="container text-center">
        <p class="text-muted">
            {% if user.is_authenticated %}
                <br>Logged in as {{ user.first_name }} {{ user.last_name }}
            {% endif %}
        </p>

        <!-- Create New Day Off -->
        {% if perms.dayoff.change_dayoff %}
            <a href="/admin/dayoff/dayoff/"
            >
                <button class="btn btn-secondary">ผู้จัดกวน</button>
            </a
            >
        {% endif %}

        <!-- Create New Day Off -->
        {% if perms.dayoff.add_dayoff %}
            <a href="{% url 'create-dayoff' %}">
                <button class="btn btn-success">ขี้เกียจแล้วโวย</button>
            </a>
        {% endif %}

        <!-- Login/Logout Button -->
        {% if not user.is_authenticated %}
            <a href="{% url 'login' %}">
                <button class="btn btn-success">เข้าสู่ระบบ</button>
            </a>
            <a href="{% url 'register' %}">
                <button class="btn btn-warning">สมัคร</button>
            </a>
        {% else %}
            <a href="{% url 'change_password' %}">
                <button class="btn btn-warning">เปลี่ยนรหัส</button>
            </a>
            <a href="{% url 'logout' %}">
                <button class="btn btn-danger">ออกไป!</button>
            </a>
        {% endif %}
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/vue"></script>
<script src="{% static 'js/main.js' %}"></script>
</body>
</html>

dayoff/templates/dayoff/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login | Poll App</title>
</head>
<body>
<h1>Login to Dayoff App</h1>
<br/>
<form method="post" action="{% url 'login' %}">
    {% csrf_token %}
    <input type="hidden" name="next_url" value="{{ next_url }}">
    <table>
        {% if error %}
            <tr>
                <td colspan="2"><span style="color: red">{{ error }}</span></td>
            </tr>
        {% endif %}
        <tr>
            <th>USERNAME:</th>
            <td>
                <input type="text" name="username" value="{{ username|default_if_none:"" }}">
            </td>
        </tr>
        <tr>
            <th>PASSWORD:</th>
            <td>
                <input type="password" name="password">
            </td>
        </tr>
        <tr>
            <td colspan="2"><input type="submit" value="LOGIN"></td>
        </tr>
    </table>
</form>
</body>
</html>